services:
  - type: web
    name: hand-sign-detection-api
    runtime: python
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python api_server.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
    healthCheckPath: /health
    plan: starter