services:
  - type: web
    name: hand-sign-detection-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api_server.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    autoDeploy: true
    healthCheckPath: /health
    plan: free